//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortHorn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItem
    {
        public TodoItem()
        {
            this.IsFinished = false;
            this.IsFavourite = false;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public System.DateTime DateFinish { get; set; }
        public bool IsFinished { get; set; }
        public bool IsFavourite { get; set; }
        public int TodoListId { get; set; }
    
        public virtual TodoList ParentList { get; set; }
    }
}
