//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortHorn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Active = false;
            this.PrivilegeLevel = 0;
            this.LoginToken = new HashSet<LoginToken>();
            this.TodoLists = new HashSet<TodoList>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public string ActivationToken { get; set; }
        public int PrivilegeLevel { get; set; }
        public string DateRegistered { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
    
        public virtual ICollection<LoginToken> LoginToken { get; set; }
        public virtual ICollection<TodoList> TodoLists { get; set; }
    }
}
